Update FCE.yml

diff --git a/.github/workflows/FCE.yml b/.github/workflows/FCE.yml
--- a/.github/workflows/FCE.yml
+++ b/.github/workflows/FCE.yml
@@ -17,10 +17,32 @@ jobs:
   FCE:
     name: ${{ github.event.inputs.track }}
     runs-on: ubuntu-latest
-    container: ghcr.io/offici5l/fce-docker:latest
 
-    steps:
+    steps:  
       - uses: actions/checkout@v4  
+
+      - name: cache  
+        id: cache  
+        uses: actions/cache@v4  
+        with:  
+          path: |  
+            ~/.local/lib/python3*/site-packages  
+            tools  
+          key: ${{ runner.os }}-cache-${{ hashFiles('**/tools/*') }}  
+          restore-keys: |  
+            ${{ runner.os }}-cache-  
+
+      - name: install  
+        if: steps.cache.outputs.cache-hit != 'true'  
+        run: |  
+          if [ ! -d tools ]; then  
+            sudo apt-get update && sudo apt-get install -y python3-pip p7zip-full aria2  
+            git clone https://github.com/vm03/payload_dumper.git tools  
+            aria2c -o erofs-utils.zip https://github.com/sekaiacg/erofs-utils/releases/download/v1.8.1-240810/erofs-utils-v1.8.1-gddbed144-Linux_x86_64-2408101422.zip  
+            7z x erofs-utils.zip -otools  
+            pip install -r ./tools/requirements.txt  
+            rm -f erofs-utils.zip  
+          fi  
 
       - name: download  
         run: |  
@@ -30,6 +52,7 @@ jobs:
 
       - name: EC  
         run: |
+          
           boot_img="false"
           init_boot="false"
           vendor_boot="false"
@@ -38,7 +61,7 @@ jobs:
             echo "payload.bin found, extracting images..."
             for img in boot init_boot vendor_boot; do
               echo "Attempting to extract $img..."
-              payload_dumper.py --out . --images $img payload.bin || echo "$img not found in payload.bin, skipping..."
+              ./tools/payload_dumper.py --out . --images $img payload.bin || echo "$img not found in payload.bin, skipping..."
             done
           else
             echo "payload.bin not found, using existing images..."
